name: Slack post start

runs:
  using: "composite"
  steps:
    - name: Slack post
      id: slack-post
      uses: ./.github/actions/slack-post
      with:
        text: '[${{ github.event.inputs.env }}] ${{ github.workflow }} を開始しました'
        color-code: blue
